# -*- coding: utf-8 -*-
"""Nomidade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12iuEo-lzjlBj8oEA6JNTBlABCsYMhXKf
"""

name = input('Digite aqui seu nome: ')
idade = int(input("Digite a sua idade: "))



